# yaml 配置
# 关联多个容器
version: "3.7"
services:
  mysql830:
    image: "mysql:8.3.0"
    ports:
      - "13306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "islet"
      MYSQL_PASSWORD: "root1234"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis724:
    image: "redis:7.2.4"
    ports:
      - "6379:6379"
  islet_app:
    build: .
    command: sh -c "./wait-for.sh mysql830:13306 redis724:6379 -- ./islet_app ./conf/config.yaml"
    depends_on:
      - mysql830
      - redis724
    ports:
      - "8888:8081"
