name: "islet"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2024-03-01"
machine_id: 1

log:
  level: "debug"
  filename: "islet.log"
  max_size: 200
  max_age: 30 # 30 days
  max_backups: 7

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: ljk123456
  dbname: islet
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: 127.0.0.1
  password: ljk123456
  port: 6379
  db: 1
  pool_size: 100

