name: "islet"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2024-03-01"
machine_id: 1

log:
  level: "debug"
  filename: "islet.log"
  max_size: 200
  max_age: 30 # 30 days
  max_backups: 7

mysql:
  host: mysql830
  port: 3306
  user: root
  password: "root1234"
  dbname: islet
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: redis724
  password: ""
  port: 6379
  db: 0
  pool_size: 100

